### Recreate the example to understand lee's algorithm

#### Wave propogation through FIFO and BFS , then perform retrace backtrack to connect the macro with same net_id

In [1]:
import numpy as np
import copy
from queue import Queue
MAP_SIZE = 16
path_map = np.array([[0 for y in range(MAP_SIZE)] for x in range(MAP_SIZE)])
location_map = np.array([[0 for y in range(MAP_SIZE)] for x in range(MAP_SIZE)])

# Framing , double fan out, pick points


# (x,y)
# Assign example location map
# Macro 1
location_map[2:4,10:14] = 9
location_map[10:12,4:6] = 9
# Macro 2
location_map[2:5,2:6] = 4
location_map[12:14,11:14] = 4


In [2]:
location_map

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 4, 4, 4, 4, 0, 0, 0, 0, 9, 9, 9, 9, 0, 0],
       [0, 0, 4, 4, 4, 4, 0, 0, 0, 0, 9, 9, 9, 9, 0, 0],
       [0, 0, 4, 4, 4, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 9, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 9, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [3]:
path_map = copy.deepcopy(location_map)

### Lee's algorithm using location map

In [4]:
## Given net_id,loc_x and loc_y
net_id_1 = 9
loc_x_11 = 5  #source
loc_y_11 = 10
loc_x_21 = 11 #sink
loc_y_21 = 3

net_id_2 = 4
loc_x_12 = 4  #source
loc_y_12 = 2
loc_x_22 = 13 # sink
loc_y_22 = 13

In [5]:
def checkValidNeighbor(location_map,path_map,neighbor):
    x = neighbor[1]
    y = neighbor[0]
    if (x < MAP_SIZE and y < MAP_SIZE and x>=0 and y>=0) and (path_map[y,x] == 0 and location_map[y,x] == 0):
        return True
    return False

### Fill path

In [6]:
def fillpath(src_x,src_y,dst_x,dst_y,location_map,path_map):
    q = Queue(maxsize=100)
    q.put([src_y,src_x,1])

    break_flag = 0
    while not q.empty():
        current_node = q.get()
        cur_x = current_node[1]
        cur_y = current_node[0]
        cur_seq = current_node[2]

        nxt_seq = cur_seq + 1
        if nxt_seq == 4:
            nxt_seq = 1

        # Down,up,right,left
        for neighbor in [[cur_y+1,cur_x,nxt_seq],[cur_y-1,cur_x,nxt_seq],[cur_y,cur_x+1,nxt_seq],[cur_y,cur_x-1,nxt_seq]]:
            neighbor_x = neighbor[1]
            neighbor_y = neighbor[0]

            # If current node is neighbor
            if neighbor_x == dst_x and  neighbor_y == dst_y:
                path_map[neighbor_y,neighbor_x] = cur_seq
                break_flag = 1
                break
            elif checkValidNeighbor(location_map,path_map,neighbor) == True:
                path_map[neighbor_y,neighbor_x] = cur_seq
                q.put(neighbor)

        if break_flag == 1:
            break

In [7]:
fillpath(loc_x_11,loc_y_11,loc_x_21,loc_y_21,location_map,path_map)

In [8]:
path_map

array([[0, 0, 0, 0, 1, 3, 2, 3, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 3, 2, 1, 2, 3, 1, 0, 0, 0, 0, 0, 0],
       [0, 3, 4, 4, 4, 4, 3, 1, 2, 3, 9, 9, 9, 9, 0, 0],
       [3, 2, 4, 4, 4, 4, 2, 3, 1, 2, 9, 1, 9, 9, 0, 0],
       [2, 1, 4, 4, 4, 4, 1, 2, 3, 1, 2, 3, 0, 0, 0, 0],
       [1, 3, 2, 1, 3, 2, 3, 1, 2, 3, 1, 2, 3, 0, 0, 0],
       [3, 2, 1, 3, 2, 1, 2, 3, 1, 2, 3, 1, 2, 3, 0, 0],
       [2, 1, 3, 2, 1, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 0],
       [1, 3, 2, 1, 3, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3],
       [3, 2, 1, 3, 2, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2],
       [1, 3, 2, 1, 9, 9, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1],
       [2, 1, 3, 2, 9, 9, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2],
       [3, 2, 1, 3, 2, 1, 3, 1, 2, 3, 1, 4, 4, 4, 2, 3],
       [1, 3, 2, 1, 3, 2, 1, 2, 3, 1, 2, 4, 4, 4, 3, 0],
       [2, 1, 3, 2, 1, 3, 2, 3, 1, 2, 3, 1, 2, 3, 0, 0],
       [3, 2, 1, 3, 2, 1, 3, 1, 2, 3, 1, 2, 3, 0, 0, 0]])

### Retrace path

In [9]:
def retrace_path(net_id,src_x,src_y,dst_x,dst_y,location_map,path_map):
    found_flag = 0
    # From terminal do backtracking follow the traverse sequence 3 2 1
    cur_node = [dst_y,dst_x,path_map[dst_y,dst_x]]
    while True:
        cur_x   = cur_node[1]
        cur_y   = cur_node[0]
        cur_seq = cur_node[2]

        # Down,up,right,left
        for neighbor in [[cur_y+1,cur_x,path_map[cur_y+1,cur_x]],[cur_y-1,cur_x,path_map[cur_y-1,cur_x]],\
                         [cur_y,cur_x+1,path_map[cur_y,cur_x+1]],[cur_y,cur_x-1,path_map[cur_y,cur_x-1]]]:

            neighbor_x   = neighbor[1]
            neighbor_y   = neighbor[0]
            neighbor_seq = neighbor[2]

            if cur_seq == 1:
                nxt_seq = 3
            else:
                nxt_seq = cur_seq - 1

            # Neighbor is source break!
            if neighbor_x == src_x and neighbor_y == src_y:
                location_map[cur_y,cur_x] = net_id
                path_map[cur_y,cur_x] = net_id
                found_flag = 1
                break

            if neighbor_seq == nxt_seq and (neighbor_x < MAP_SIZE and neighbor_y < MAP_SIZE and neighbor_x >=0 and neighbor_y>=0):
                location_map[cur_y,cur_x] = net_id
                path_map[cur_y,cur_x] = net_id
                cur_node = neighbor
                break

        if found_flag == 1:
            break

In [10]:
retrace_path(net_id_1,loc_x_11,loc_y_11,loc_x_21,loc_y_21,location_map,path_map)

In [11]:
location_map

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 4, 4, 4, 4, 0, 0, 0, 0, 9, 9, 9, 9, 0, 0],
       [0, 0, 4, 4, 4, 4, 0, 0, 0, 0, 9, 9, 9, 9, 0, 0],
       [0, 0, 4, 4, 4, 4, 0, 0, 0, 0, 0, 9, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 0],
       [0, 0, 0, 0, 9, 9, 9, 9, 9, 9, 9, 9, 0, 0, 0, 0],
       [0, 0, 0, 0, 9, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [12]:
path_map

array([[0, 0, 0, 0, 1, 3, 2, 3, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 3, 2, 1, 2, 3, 1, 0, 0, 0, 0, 0, 0],
       [0, 3, 4, 4, 4, 4, 3, 1, 2, 3, 9, 9, 9, 9, 0, 0],
       [3, 2, 4, 4, 4, 4, 2, 3, 1, 2, 9, 9, 9, 9, 0, 0],
       [2, 1, 4, 4, 4, 4, 1, 2, 3, 1, 2, 9, 0, 0, 0, 0],
       [1, 3, 2, 1, 3, 2, 3, 1, 2, 3, 1, 9, 3, 0, 0, 0],
       [3, 2, 1, 3, 2, 1, 2, 3, 1, 2, 3, 9, 2, 3, 0, 0],
       [2, 1, 3, 2, 1, 3, 1, 2, 3, 1, 2, 9, 1, 2, 3, 0],
       [1, 3, 2, 1, 3, 2, 3, 1, 2, 3, 1, 9, 3, 1, 2, 3],
       [3, 2, 1, 3, 2, 1, 2, 3, 1, 2, 3, 9, 2, 3, 1, 2],
       [1, 3, 2, 1, 9, 9, 9, 9, 9, 9, 9, 9, 1, 2, 3, 1],
       [2, 1, 3, 2, 9, 9, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2],
       [3, 2, 1, 3, 2, 1, 3, 1, 2, 3, 1, 4, 4, 4, 2, 3],
       [1, 3, 2, 1, 3, 2, 1, 2, 3, 1, 2, 4, 4, 4, 3, 0],
       [2, 1, 3, 2, 1, 3, 2, 3, 1, 2, 3, 1, 2, 3, 0, 0],
       [3, 2, 1, 3, 2, 1, 3, 1, 2, 3, 1, 2, 3, 0, 0, 0]])

In [13]:
path_map = copy.deepcopy(location_map)

### Repeat for second net

In [14]:
fillpath(loc_x_12,loc_y_12,loc_x_22,loc_y_22,location_map,path_map)

In [15]:
retrace_path(net_id_2,loc_x_12,loc_y_12,loc_x_22,loc_y_22,location_map,path_map)

In [16]:
location_map

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 0],
       [0, 0, 4, 4, 4, 4, 0, 0, 0, 0, 9, 9, 9, 9, 4, 0],
       [0, 0, 4, 4, 4, 4, 0, 0, 0, 0, 9, 9, 9, 9, 4, 0],
       [0, 0, 4, 4, 4, 4, 0, 0, 0, 0, 0, 9, 0, 0, 4, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 4, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 4, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 4, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 4, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 4, 0],
       [0, 0, 0, 0, 9, 9, 9, 9, 9, 9, 9, 9, 0, 0, 4, 0],
       [0, 0, 0, 0, 9, 9, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 4, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 4, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])