In [1]:
import numpy as np
import copy
MAP_SIZE = 16

# Do data structure augmentation on both map
# Path map, 0 as passable, 1 as block, 2,3 as seq for further optimization
path_map = np.array([[0 for y in range(MAP_SIZE+2)] for x in range(MAP_SIZE+2)])

# Location map, 0 as passable, 1 as blocked
location_map = np.array([[0 for y in range(MAP_SIZE+2)] for x in range(MAP_SIZE+2)])

# Wall padding for boundary condition handling
for y in range(MAP_SIZE+2):
    for x in range(MAP_SIZE+2):
        if y == 0 or x == 0 or y == MAP_SIZE+1 or x == MAP_SIZE+1:
            path_map[y,x] = 3
            location_map[y,x] = 1

# Thus all target is offsetted by (1,1)
# (x,y)
# Assign example location map
# Macro 1
location_map[3:5,11:15] = 9
location_map[11:13,5:7] = 9
# Macro 2
location_map[3:6,3:7] = 4
location_map[13:15,12:15] = 4

In [2]:
def copy_loc_path(path_map,location_map):
    for y in range(MAP_SIZE+2):
        for x in range(MAP_SIZE+2):
            if location_map[y,x] != 0:
                path_map[y,x] = 3
            else:
                path_map[y,x] = 0
    return

In [3]:
copy_loc_path(path_map,location_map)

In [4]:
location_map

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 4, 4, 4, 4, 0, 0, 0, 0, 9, 9, 9, 9, 0, 0, 1],
       [1, 0, 0, 4, 4, 4, 4, 0, 0, 0, 0, 9, 9, 9, 9, 0, 0, 1],
       [1, 0, 0, 4, 4, 4, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 9, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 9, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [5]:
path_map

array([[3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3],
       [3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3],
       [3, 0, 0, 3, 3, 3, 3, 0, 0, 0, 0, 3, 3, 3, 3, 0, 0, 3],
       [3, 0, 0, 3, 3, 3, 3, 0, 0, 0, 0, 3, 3, 3, 3, 0, 0, 3],
       [3, 0, 0, 3, 3, 3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3],
       [3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3],
       [3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3],
       [3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3],
       [3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3],
       [3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3],
       [3, 0, 0, 0, 0, 3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3],
       [3, 0, 0, 0, 0, 3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3],
       [3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 3, 0, 0, 3],
       [3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 3, 0, 0, 3],
       [3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [6]:
## Given net_id,loc_x and loc_y
net_id_1 = 9
src_x_1 = 5  #source
src_y_1 = 10
dst_x_1 = 11 #sink
dst_y_1 = 3

net_id_2 = 4
src_x_2 = 4  #source
src_y_2 = 2
dst_x_2 = 13 # sink
dst_y_2 = 13

In [7]:
path_map_nxt = copy.deepcopy(path_map)

In [8]:
def adjacent_has_1_2(path_map,dst_y,dst_x):
    if path_map[dst_y+1,dst_x] == 1 or path_map[dst_y-1,dst_x]==1 or \
       path_map[dst_y,dst_x+1]==1 or path_map[dst_y,dst_x-1]==1 \
       or path_map[dst_y+1,dst_x] == 2 or path_map[dst_y-1,dst_x]==2 or \
       path_map[dst_y,dst_x+1]==2 or path_map[dst_y,dst_x-1]==2:
        return True
    else:
        return False

In [9]:
def fillpath(src_x,src_y,dst_x,dst_y,location_map,path_map):
    # Initailize source, all source must be offsetted by (1,1)
    cur_y = src_y+1
    cur_x = src_x+1
    target_y = dst_y+1
    target_x = dst_x+1
    for neighbor in [[cur_y+1,cur_x],[cur_y-1,cur_x],[cur_y,cur_x+1],[cur_y,cur_x-1]]:
        neighbor_x = neighbor[1]
        neighbor_y = neighbor[0]
        if location_map[neighbor_y,neighbor_x] == 0 and path_map[neighbor_y,neighbor_x] == 0:
            path_map[neighbor_y,neighbor_x] = 1

    cnt = 1
    path_map_nxt = copy.deepcopy(path_map)
    while True:
        if cnt == 4:
            cnt = 0

        if adjacent_has_1_2(path_map,target_y,target_x):
            return path_map,cnt

        for cur_y in range(1,MAP_SIZE+1):
            for cur_x in range(1,MAP_SIZE+1):
                if location_map[cur_y,cur_x] == 0 and path_map[cur_y,cur_x] == 0:
                    # Down,up,right,left
                    if adjacent_has_1_2(path_map,cur_y,cur_x):
                        if cnt == 0:
                            path_map_nxt[cur_y,cur_x] = 1
                        elif cnt == 1:
                            path_map_nxt[cur_y,cur_x] = 1
                        elif cnt == 2:
                            path_map_nxt[cur_y,cur_x] = 2
                        elif cnt == 3:
                            path_map_nxt[cur_y,cur_x] = 2

        # print(path_map_nxt)
        path_map = copy.deepcopy(path_map_nxt)
        cnt += 1

In [10]:
path_map,cnt = fillpath(src_x_1,src_y_1,dst_x_1,dst_y_1,location_map,path_map)

In [11]:
path_map,cnt

(array([[3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
        [3, 0, 0, 0, 0, 0, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 3],
        [3, 0, 0, 0, 0, 2, 2, 1, 2, 2, 0, 0, 0, 0, 0, 0, 0, 3],
        [3, 0, 2, 3, 3, 3, 3, 1, 1, 2, 2, 3, 3, 3, 3, 0, 0, 3],
        [3, 2, 2, 3, 3, 3, 3, 2, 1, 1, 2, 3, 3, 3, 3, 0, 0, 3],
        [3, 2, 1, 3, 3, 3, 3, 2, 2, 1, 1, 2, 2, 0, 0, 0, 0, 3],
        [3, 1, 1, 2, 2, 1, 1, 1, 2, 2, 1, 1, 2, 2, 0, 0, 0, 3],
        [3, 1, 2, 2, 1, 1, 2, 1, 1, 2, 2, 1, 1, 2, 2, 0, 0, 3],
        [3, 2, 2, 1, 1, 2, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 0, 3],
        [3, 2, 1, 1, 2, 2, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 3],
        [3, 1, 1, 2, 2, 1, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 3],
        [3, 2, 1, 1, 2, 3, 3, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 3],
        [3, 2, 2, 1, 1, 3, 3, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 3],
        [3, 1, 2, 2, 1, 1, 2, 2, 2, 1, 1, 2, 3, 3, 3, 2, 2, 3],
        [3, 1, 1, 2, 2, 1, 1, 2, 1, 1, 2, 2, 3, 3, 3, 2, 0, 3],
        [3, 2, 1, 1, 2, 2, 1, 1, 1, 2, 2

### Notice that you can reuse the cnt final state for retracing, retrace simply subtracts the cnt

In [12]:
def retrace_path(net_id,src_x,src_y,dst_x,dst_y,location_map,path_map,cnt):
    # Find the first label and starting seq from dst, implement FSM in python
    cur_x   = dst_x + 1
    cur_y   = dst_y + 1
    target_x = src_x + 1
    target_y = src_y + 1

    # From the cnt given, counts back
    while True:
        if cnt == 0:
            nxt_count = 3
        else:
            nxt_count = cnt-1

        if (cur_y+1 ==target_y and cur_x == target_x) or (cur_y-1 == target_y and cur_x == target_x) or (cur_y==target_y and cur_x+1 == target_x)\
        or (cur_y == target_y and cur_x-1 == target_x):
            return

        if nxt_count == 2 or nxt_count == 3: # Expect 2
            # Down
            if path_map[cur_y+1,cur_x] == 2:
                cur_y = cur_y + 1
            # Up
            elif path_map[cur_y-1,cur_x] == 2:
                cur_y = cur_y-1
            # Right
            elif path_map[cur_y,cur_x+1] == 2:
                cur_x = cur_x+1
            # Left
            elif path_map[cur_y,cur_x-1] == 2:
                cur_x = cur_x-1

        elif nxt_count == 0 or nxt_count == 1: # Expect 1
            # Down
            if path_map[cur_y+1,cur_x] == 1:
                cur_y = cur_y + 1
            # Up
            elif path_map[cur_y-1,cur_x] == 1:
                cur_y = cur_y-1
            # Right
            elif path_map[cur_y,cur_x+1] == 1:
                cur_x = cur_x+1
            # Left
            elif path_map[cur_y,cur_x-1] == 1:
                cur_x = cur_x-1

        cnt = nxt_count
        location_map[cur_y,cur_x] = net_id
        path_map[cur_y,cur_x] = 3

In [13]:
retrace_path(net_id_1,src_x_1,src_y_1,dst_x_1,dst_y_1,location_map,path_map,cnt)

In [14]:
location_map

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 4, 4, 4, 4, 0, 0, 0, 0, 9, 9, 9, 9, 0, 0, 1],
       [1, 0, 0, 4, 4, 4, 4, 0, 0, 0, 0, 9, 9, 9, 9, 0, 0, 1],
       [1, 0, 0, 4, 4, 4, 4, 0, 0, 0, 0, 0, 9, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 9, 9, 9, 9, 9, 9, 9, 9, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 9, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [15]:
location_map

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 4, 4, 4, 4, 0, 0, 0, 0, 9, 9, 9, 9, 0, 0, 1],
       [1, 0, 0, 4, 4, 4, 4, 0, 0, 0, 0, 9, 9, 9, 9, 0, 0, 1],
       [1, 0, 0, 4, 4, 4, 4, 0, 0, 0, 0, 0, 9, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 9, 9, 9, 9, 9, 9, 9, 9, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 9, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [16]:
path_map

array([[3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 0, 0, 0, 0, 0, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 3],
       [3, 0, 0, 0, 0, 2, 2, 1, 2, 2, 0, 0, 0, 0, 0, 0, 0, 3],
       [3, 0, 2, 3, 3, 3, 3, 1, 1, 2, 2, 3, 3, 3, 3, 0, 0, 3],
       [3, 2, 2, 3, 3, 3, 3, 2, 1, 1, 2, 3, 3, 3, 3, 0, 0, 3],
       [3, 2, 1, 3, 3, 3, 3, 2, 2, 1, 1, 2, 3, 0, 0, 0, 0, 3],
       [3, 1, 1, 2, 2, 1, 1, 1, 2, 2, 1, 1, 3, 2, 0, 0, 0, 3],
       [3, 1, 2, 2, 1, 1, 2, 1, 1, 2, 2, 1, 3, 2, 2, 0, 0, 3],
       [3, 2, 2, 1, 1, 2, 2, 2, 1, 1, 2, 2, 3, 1, 2, 2, 0, 3],
       [3, 2, 1, 1, 2, 2, 1, 2, 2, 1, 1, 2, 3, 1, 1, 2, 2, 3],
       [3, 1, 1, 2, 2, 1, 1, 1, 2, 2, 1, 1, 3, 2, 1, 1, 2, 3],
       [3, 2, 1, 1, 2, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 1, 1, 3],
       [3, 2, 2, 1, 1, 3, 3, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 3],
       [3, 1, 2, 2, 1, 1, 2, 2, 2, 1, 1, 2, 3, 3, 3, 2, 2, 3],
       [3, 1, 1, 2, 2, 1, 1, 2, 1, 1, 2, 2, 3, 3, 3, 2, 0, 3],
       [3, 2, 1, 1, 2, 2, 1, 1, 1, 2, 2, 1, 1, 2, 2, 0,

- Clear path map

In [17]:
for y in range(MAP_SIZE+2):
    for x in range(MAP_SIZE+2):
        if path_map[y,x] != 3:
            path_map[y,x] = 0

In [18]:
def clear_pathmap(path_map):
    for y in range(MAP_SIZE+2):
        for x in range(MAP_SIZE+2):
            if path_map[y,x] != 3:
                path_map[y,x] = 0

    return

In [19]:
net_id_2 = 4
src_x_2 = 4  #source
src_y_2 = 4
dst_x_2 = 13 # sink
dst_y_2 = 13

In [20]:
path_map,cnt = fillpath(src_x_2,src_y_2,dst_x_2,dst_y_2,location_map,path_map)

In [21]:
path_map

array([[3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 1, 1, 1, 2, 1, 1, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 3],
       [3, 1, 2, 1, 1, 1, 2, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 3],
       [3, 2, 2, 3, 3, 3, 3, 1, 2, 2, 1, 3, 3, 3, 3, 2, 1, 3],
       [3, 2, 1, 3, 3, 3, 3, 1, 1, 2, 2, 3, 3, 3, 3, 1, 1, 3],
       [3, 1, 1, 3, 3, 3, 3, 2, 1, 1, 2, 2, 3, 2, 2, 1, 2, 3],
       [3, 1, 2, 2, 1, 1, 1, 2, 2, 1, 1, 2, 3, 1, 2, 2, 2, 3],
       [3, 1, 1, 2, 2, 1, 2, 2, 1, 1, 2, 2, 3, 0, 1, 2, 1, 3],
       [3, 2, 1, 1, 2, 2, 2, 1, 1, 2, 2, 1, 3, 0, 0, 1, 0, 3],
       [3, 2, 2, 1, 1, 2, 1, 1, 2, 2, 1, 1, 3, 0, 0, 0, 0, 3],
       [3, 1, 2, 2, 1, 1, 1, 2, 2, 1, 1, 2, 3, 1, 0, 0, 0, 3],
       [3, 1, 1, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 2, 1, 0, 0, 3],
       [3, 2, 1, 1, 2, 3, 3, 1, 1, 2, 2, 1, 1, 2, 2, 1, 0, 3],
       [3, 2, 2, 1, 1, 1, 2, 2, 1, 1, 2, 2, 3, 3, 3, 0, 0, 3],
       [3, 1, 2, 2, 1, 2, 2, 1, 1, 2, 2, 1, 3, 3, 3, 0, 0, 3],
       [3, 1, 1, 2, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 0,

In [22]:
retrace_path(net_id_2,src_x_2,src_y_2,dst_x_2,dst_y_2,location_map,path_map,cnt)

In [23]:
location_map

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 4, 4, 4, 4, 0, 0, 0, 0, 9, 9, 9, 9, 0, 0, 1],
       [1, 0, 0, 4, 4, 4, 4, 0, 0, 0, 0, 9, 9, 9, 9, 0, 0, 1],
       [1, 0, 0, 4, 4, 4, 4, 0, 0, 0, 0, 0, 9, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 4, 4, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 4, 9, 9, 9, 9, 9, 9, 9, 9, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 4, 9, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 4, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 4, 0,