In [381]:
import numpy as np

PATTERN_TO_DEBUG = 4

def toDec(hexstr,BIT):
    msb4bits = hexstr[0]
    n = int(msb4bits, 16)
    if n >= 8:
        p = -1*pow(2,BIT-1)
        addend = int(str(n-8) + hexstr[1:], 16)
        return str( p + addend)
    else:
        return str(int(hexstr, 16))

def int2hex(num,bit_width):
    if num<0:
        num = (1 << bit_width) + num
    hex_string = hex(num)[2:]
    return '{:0>{width}}'.format(hex_string,width = (bit_width+3)//4)

NEGATE = {'1': '0', '0': '1'}
def negate(value):
    return ''.join(NEGATE[x] for x in value)

def twocomplement(n, size_in_bits):
    # print(n)
    number = int(n)
    if number < 0:
        return negate(bin(abs(number) - 1)[2:]).rjust(size_in_bits, '1')
    else:
        return bin(number)[2:].rjust(size_in_bits, '0')

NEGATE = {'1': '0', '0': '1'}
def negate(value):
    return ''.join(NEGATE[x] for x in value)

def reverseRow(data, index):

    cols = len(data[index])
    for i in range(cols // 2):
        temp = data[index][i]
        data[index][i] = data[index][cols - i - 1]
        data[index][cols - i - 1] = temp

    return data

# Rotate Matrix by 180 degrees
def rotateMatrix(data):

    rows = len(data)
    cols = len(data[0])

    if (rows % 2):
        # If N is odd reverse the middle
        # row in the matrix
        data = reverseRow(data, len(data) // 2)

        # Swap the value of matrix [i][j] with
        # [rows - i - 1][cols - j - 1] for half
        # the rows size.
        for i in range(rows // 2):
            for j in range(cols):
                temp = data[i][j]
                data[i][j] = data[rows - i - 1][cols - j - 1]
                data[rows - i - 1][cols - j - 1] = temp
        return data

def twocomplement(n, size_in_bits):
    # print(n)
    number = int(n)
    if number < 0:
        return negate(bin(abs(number) - 1)[2:]).rjust(size_in_bits, '1')
    else:
        return bin(number)[2:].rjust(size_in_bits, '0')


In [382]:
with open('input.txt', 'r') as file:
  file_in = file.readlines()

NUM = int(file_in[0])

# print(file_in)
for i in range(NUM):
  img_16 = []
  kernal_16 = []
  matrix_idx = []
  mode = []

  # MATRIX SIZE
  matrix_in_idx = int(file_in[1 + 65 * i + 0])

  if matrix_in_idx == 0:
     matrix_size = 8
  elif matrix_in_idx == 1:
     matrix_size = 16
  else:
     matrix_size = 32

  for j in range(16):
    img_in = np.array([int(toDec(val,8)) for val in file_in[1 + 65 * i + (1+j)].split()])
    img_16.append(np.reshape(img_in,(matrix_size,matrix_size)))

  for k in range(16):
    kernal_in = np.array([int(toDec(val,8)) for val in file_in[1 + 65 * i + (17+k)].split()])
    kernal_16.append(np.reshape(kernal_in,(5,5)))


  for idx in range(16):
    mode.append(int(file_in[1 + 65 * i + (33+idx*2)])) #0 2 4
    matrix_idx.append(np.array([int(val) for val in file_in[1 + 65 * i + (34+idx*2)].split()]))# 1 3 5

  if i == PATTERN_TO_DEBUG:
    break

In [383]:
mode[0]

0

In [384]:
matrix_idx[6]

array([ 6, 15])

In [385]:
img_16[13]

array([[  58,  -69,   70, -100,  118,   57,  -95,  -47, -122,  -25,  -69,
         119,    5,  101,  -67, -115],
       [ -15,  115,   40,  -81, -116,  -92,   81,  -17, -106,   50,   70,
          35,  -46,  -99,   65,  -53],
       [  34,   31,  -44,  -64,  104,  -68,   25,   92,   22,  120,  -19,
          55,   98,  -75,  -20,  120],
       [ -46,    7,  120,  -36,   89,   -8,  -97,  -17,  -44,  -21,   57,
         -69,   -4,  -66,   27, -106],
       [ -29,  -56,  -51,   75,   26,   58,  -97,  107,  -78,  -83,  -53,
          18,   60,  107,   62,  -59],
       [-103,  -37,  -70,   53,   10,  115,   96,   81, -105,   82,   38,
         -37,  -93,  -16,    6,   64],
       [ 112,   84, -114,  -18,   70,   58,   17,  -98,  -50,    8,   24,
         -36,  -76, -102,   70,  -91],
       [ -55,  117, -113, -104,  -62,  -23,   51,  -82,  -34,   60,   20,
         -50,   93,  -22,   -7, -126],
       [ -79,  -90,   25,    0, -101,  -22,  -86,  102,   57,   62,  -69,
         -68,   70, -1

In [386]:
kernal_16[8]

array([[ -34,   -7,   85,   30,  -30],
       [ -72,  -87,  102,  107,  110],
       [ 107,  100,  -57,  -90, -113],
       [  14,   80,   14,  124,  117],
       [  30, -101,  -56,  121,   60]])

In [387]:
matrix_idx[0]

array([ 2, 14])

In [388]:
matrix_size

16

## Convolution

In [389]:
img = img_16[13]
kernal = kernal_16[9]

convoluted_results = np.zeros((matrix_size-4,matrix_size-4))
for i in range(matrix_size-4):
    for j in range(matrix_size-4):
        conv = 0
        for k in range(5):
            for l in range(5):
                conv += kernal[k,l] * img[i+k,j+l]

        convoluted_results[i,j] = conv

In [390]:
convoluted_results

array([[  4583.,  -5202.,   4295.,  16231., -48008.,  20264., -19893.,
         -8263., -20252., -24039.,  44814., -26779.],
       [ 36156., -20739.,   2548.,  33600., -39714.,  34440.,    461.,
        -15002.,  22383.,   1594.,  23498.,  -3589.],
       [ 36945.,   3138.,  10366.,  55980., -13964.,  16391.,  32479.,
        -54417.,   5123., -12361.,  24490., -24686.],
       [  2012.,  21938., -17250.,   5502., -32319.,  11314., -25825.,
        -37388.,  23975., -22540., -27745., -32164.],
       [-66785., -27768.,   1775.,  14093., -33619.,   8608., -20927.,
         -3012.,  28868.,  -7515., -17734., -39341.],
       [-22863., -53929., -20276., -21165.,  31257.,  29218., -31996.,
        -24809.,  -2928., -50637.,   5059., -58661.],
       [-14090.,  -8609.,  -5183., -30465.,  -4616., -25927.,  -3030.,
        -36036.,  16443., -70611.,   2137., -22739.],
       [ -2131., -22816., -66766.,  35077., -20547.,   1310., -15435.,
        -14071.,  -7997., -34634.,  17842., -41302.],


## Maxpooling

In [391]:
convoluted_img_width = len(convoluted_results)

In [392]:
max_pooling_results = np.zeros((convoluted_img_width//2,convoluted_img_width//2))

for i in range(0,convoluted_img_width,2):
    for j in range(0,convoluted_img_width,2):
        max_pooling_results[i//2,j//2] = max(convoluted_results[i,j],convoluted_results[i+1,j],\
                                                convoluted_results[i+1,j+1],convoluted_results[i,j+1])

In [393]:
max_pooling_results

array([[ 36156.,  33600.,  34440.,    461.,  22383.,  44814.],
       [ 36945.,  55980.,  16391.,  32479.,  23975.,  24490.],
       [-22863.,  14093.,  31257.,  -3012.,  28868.,   5059.],
       [ -2131.,  35077.,   1310.,  -3030.,  16443.,  17842.],
       [ 35850.,  35127.,  12487.,  14285.,  21146.,    568.],
       [ 38292.,  46610.,  30451.,  32608.,  34144.,    244.]])

### Merged Convolution and max pooling

In [394]:
img_16[2]

array([[ 103,  -34,  -60, -109,  -73,  -52,  -88,   97,   25,  109,  -26,
         -35,  -76,   43,  -78,    1],
       [ -25,   58,  -67,  105,   21,   43, -127,   46,  -96,  -37,   37,
          43,   44,   -2,  -70,   33],
       [ -13,   32,  -33,  -98,   10,  -90, -118,   17,  -41,  -31,   44,
         118,  -64, -106,   74,   -5],
       [  99,   27,   35, -105, -105,    7,   98,   93,   54,  -25,   90,
         109,  118, -125,   82,   58],
       [-128,  104,   53, -117, -121,  115,  121,  119,  -69,  -26,  -75,
         -76,  -88,  -30,  102,  -68],
       [ 120,   76,   18,   -2,  -99,  114,  -33,   48,   99,   74,   -1,
         -99,  -27,   84,    4,  124],
       [ -62,  -76, -108,  -23,  -92,   65,  -46,  -60,  -93, -117,  101,
         103,   16, -110,  -70,  116],
       [  90,    3,  -27,   73,  -93,   50,    3,  -13,  112,   -1,  100,
          27,  -61,   71,   76,  -85],
       [  39, -124,   48, -100,   33,  -22, -114,   50, -127,   21,  -45,
           5,  127,  -

In [395]:
kernal_16[3]

array([[ 124,   12,   46,  109, -126],
       [  72,   97,  -97,   15,   14],
       [ -54,   86,  -66,   17,  -16],
       [ 107,    0,   71,  -87,   -8],
       [  -5,  -96,   58, -119,  -37]])

In [396]:
img = img_16[13]
kernal = kernal_16[9]

In [397]:
max_pooling_results = np.zeros((convoluted_img_width//2,convoluted_img_width//2))
for img_yptr in range(0,matrix_size-4,2):
    for img_xptr in range(0,matrix_size-4,2):
        # print(img_yptr)

        temp_max = -999999
        # 4 times convolution to quickly get values needed for max pooling
        for mp_window_y in range(2):
            for mp_window_x in range(2):
                conv = 0
                idx_x = img_xptr+mp_window_x
                idx_y = img_yptr+mp_window_y
                for k_yptr in range(5):
                    # Uses High level modeling for fast MAC, img_x_cord[x] and kernal_x_cord[x]
                    for k_xptr in range(5): # Unrolling the x_ptr
                        conv += kernal[k_yptr,k_xptr] * img[idx_y+k_yptr,idx_x+k_xptr]

                if conv>=67:
                    print(conv)
                    print(f"(y,x) = {img_yptr,img_xptr}")
                    print(f"Window_y:{mp_window_y}, Window_x:{mp_window_x}")

                if (mp_window_y == 0 and mp_window_x == 0) or conv > temp_max:
                    temp_max = conv

        max_pooling_results[img_yptr//2,img_xptr//2] = temp_max

4583
(y,x) = (0, 0)
Window_y:0, Window_x:0
36156
(y,x) = (0, 0)
Window_y:1, Window_x:0
4295
(y,x) = (0, 2)
Window_y:0, Window_x:0
16231
(y,x) = (0, 2)
Window_y:0, Window_x:1
2548
(y,x) = (0, 2)
Window_y:1, Window_x:0
33600
(y,x) = (0, 2)
Window_y:1, Window_x:1
20264
(y,x) = (0, 4)
Window_y:0, Window_x:1
34440
(y,x) = (0, 4)
Window_y:1, Window_x:1
461
(y,x) = (0, 6)
Window_y:1, Window_x:0
22383
(y,x) = (0, 8)
Window_y:1, Window_x:0
1594
(y,x) = (0, 8)
Window_y:1, Window_x:1
44814
(y,x) = (0, 10)
Window_y:0, Window_x:0
23498
(y,x) = (0, 10)
Window_y:1, Window_x:0
36945
(y,x) = (2, 0)
Window_y:0, Window_x:0
3138
(y,x) = (2, 0)
Window_y:0, Window_x:1
2012
(y,x) = (2, 0)
Window_y:1, Window_x:0
21938
(y,x) = (2, 0)
Window_y:1, Window_x:1
10366
(y,x) = (2, 2)
Window_y:0, Window_x:0
55980
(y,x) = (2, 2)
Window_y:0, Window_x:1
5502
(y,x) = (2, 2)
Window_y:1, Window_x:1
16391
(y,x) = (2, 4)
Window_y:0, Window_x:1
11314
(y,x) = (2, 4)
Window_y:1, Window_x:1
32479
(y,x) = (2, 6)
Window_y:0, Window

In [398]:
max_pooling_results

array([[ 36156.,  33600.,  34440.,    461.,  22383.,  44814.],
       [ 36945.,  55980.,  16391.,  32479.,  23975.,  24490.],
       [-22863.,  14093.,  31257.,  -3012.,  28868.,   5059.],
       [ -2131.,  35077.,   1310.,  -3030.,  16443.,  17842.],
       [ 35850.,  35127.,  12487.,  14285.,  21146.,    568.],
       [ 38292.,  46610.,  30451.,  32608.,  34144.,    244.]])

In [399]:
max_pooling_results = np.zeros((convoluted_img_width//2,convoluted_img_width//2))
for img_yptr in range(0,matrix_size-4,2):
    for img_xptr in range(0,matrix_size-4,2):
        temp_max = -999999
        # 4 times convolution to quickly get values needed for max pooling
        for mp_window_y in range(2):
            for mp_window_x in range(2):
                conv = 0
                idx_y = img_yptr+mp_window_y
                idx_x = img_xptr+mp_window_x
                for k_yptr in range(5):
                    conv += kernal[k_yptr,0] * img[idx_y+k_yptr,idx_x+0]
                    conv += kernal[k_yptr,1] * img[idx_y+k_yptr,idx_x+1]
                    conv += kernal[k_yptr,2] * img[idx_y+k_yptr,idx_x+2]
                    conv += kernal[k_yptr,3] * img[idx_y+k_yptr,idx_x+3]
                    conv += kernal[k_yptr,4] * img[idx_y+k_yptr,idx_x+4]

                if (mp_window_y == 0 and mp_window_x == 0) or conv > temp_max:
                    temp_max = conv

        max_pooling_results[img_yptr//2,img_xptr//2] = temp_max

In [400]:
max_pooling_results

array([[ 36156.,  33600.,  34440.,    461.,  22383.,  44814.],
       [ 36945.,  55980.,  16391.,  32479.,  23975.,  24490.],
       [-22863.,  14093.,  31257.,  -3012.,  28868.,   5059.],
       [ -2131.,  35077.,   1310.,  -3030.,  16443.,  17842.],
       [ 35850.,  35127.,  12487.,  14285.,  21146.,    568.],
       [ 38292.,  46610.,  30451.,  32608.,  34144.,    244.]])

### Transposed convolution

In [401]:
trans_convoluted_results = np.zeros((matrix_size+4,matrix_size+4))
for i in range(matrix_size):
    for j in range(matrix_size):
        for k in range(5):
            for l in range(5):
                conv = kernal[k,l] * img[i,j]
                trans_convoluted_results[i+k,j+l] += conv

In [402]:
trans_convoluted_results

array([[ 9.2800e+02,  3.4780e+03, -2.8230e+03,  3.0640e+03, -2.2800e+03,
         5.1660e+03,  8.0910e+03, -1.0087e+04, -1.0870e+03, -9.8160e+03,
        -1.1943e+04, -8.5930e+03,  9.4300e+02,  2.7010e+03,  5.3530e+03,
         1.7610e+03, -8.9510e+03,  1.1900e+03, -5.3240e+03, -5.9800e+03],
       [-5.8800e+02,  3.9110e+03,  8.3760e+03, -1.8130e+03,  6.1170e+03,
        -2.1298e+04,  2.0421e+04, -2.8709e+04, -9.3450e+03, -2.1170e+03,
        -4.6810e+03,  9.4860e+03, -8.0810e+03,  1.0700e+04, -1.9875e+04,
         1.6919e+04, -2.7193e+04,  7.5570e+03,  9.5940e+03, -1.4716e+04],
       [-5.9780e+03,  1.4495e+04,  8.2100e+02,  1.1461e+04, -2.4510e+04,
        -1.3182e+04,  3.8680e+04, -3.3400e+03,  1.5947e+04, -2.6797e+04,
         8.3620e+03,  7.6400e+03, -7.2790e+03,  1.7821e+04, -3.1680e+03,
         3.6902e+04, -3.8660e+03, -2.6571e+04,  1.8260e+04, -5.3670e+03],
       [ 1.4660e+03, -1.4398e+04,  6.0910e+03,  3.8718e+04, -7.0210e+03,
         1.8038e+04, -1.2562e+04, -3.3562e+04,  

## Transpoed convolution with zero-padding

In [403]:
img = img_16[13]

In [404]:
img

array([[  58,  -69,   70, -100,  118,   57,  -95,  -47, -122,  -25,  -69,
         119,    5,  101,  -67, -115],
       [ -15,  115,   40,  -81, -116,  -92,   81,  -17, -106,   50,   70,
          35,  -46,  -99,   65,  -53],
       [  34,   31,  -44,  -64,  104,  -68,   25,   92,   22,  120,  -19,
          55,   98,  -75,  -20,  120],
       [ -46,    7,  120,  -36,   89,   -8,  -97,  -17,  -44,  -21,   57,
         -69,   -4,  -66,   27, -106],
       [ -29,  -56,  -51,   75,   26,   58,  -97,  107,  -78,  -83,  -53,
          18,   60,  107,   62,  -59],
       [-103,  -37,  -70,   53,   10,  115,   96,   81, -105,   82,   38,
         -37,  -93,  -16,    6,   64],
       [ 112,   84, -114,  -18,   70,   58,   17,  -98,  -50,    8,   24,
         -36,  -76, -102,   70,  -91],
       [ -55,  117, -113, -104,  -62,  -23,   51,  -82,  -34,   60,   20,
         -50,   93,  -22,   -7, -126],
       [ -79,  -90,   25,    0, -101,  -22,  -86,  102,   57,   62,  -69,
         -68,   70, -1

In [405]:
kernal = kernal_16[7]

In [406]:
kernal

array([[ -88,   33,   30,  -53,   22],
       [ 127,   62,   86,    1, -128],
       [  18,  -72,  -86,   50,   56],
       [ -38,   28,  121,   60,   35],
       [  16,   -5,    7,  -32,  -25]])

In [407]:
new_trans_convoluted_results = np.zeros((matrix_size+4,matrix_size+4))
# Note the matrix is flipped
lower_bound0 = matrix_size + 4
lower_bound1 = matrix_size + 5
lower_bound2 = matrix_size + 6
lower_bound3 = matrix_size + 7

for img_ytr in range(matrix_size+4):
    for img_xptr in range(matrix_size+4):
        conv = 0
        for k_yptr in range(5):
            # Uses High level always@* , need idx_x[x]
            for k_xptr in range(5):
                idx_y = img_ytr + k_yptr
                idx_x = img_xptr + k_xptr
                if idx_y == 0 or idx_y == 1 or idx_y == 2 or idx_y == 3 or idx_x == 0 or idx_x == 1 \
                    or idx_x == 2 or idx_x == 3:
                        conv += 0
                elif idx_y == lower_bound0 or idx_y == lower_bound1 or idx_y == lower_bound2 or idx_y == lower_bound3 \
                    or idx_x == lower_bound0 or idx_x == lower_bound1 or idx_x == lower_bound2 or idx_x == lower_bound3 :
                        conv += 0
                else:
                   # Address translation
                   conv += kernal[4-k_yptr,4-k_xptr] * img[idx_y-4,idx_x-4]

        new_trans_convoluted_results[img_ytr,img_xptr] = conv


In [408]:
rotateMatrix(kernal)

array([[ -25,  -32,    7,   -5,   16],
       [  35,   60,  121,   28,  -38],
       [  56,   50,  -86,  -72,   18],
       [-128,    1,   86,   62,  127],
       [  22,  -53,   30,   33,  -88]])

In [409]:
new_trans_convoluted_results

array([[-5.1040e+03,  7.9860e+03, -6.6970e+03,  5.9660e+03, -6.6510e+03,
        -9.3500e+03,  2.0621e+04, -5.7430e+03,  5.9100e+03,  3.0530e+03,
         1.9880e+03, -8.0670e+03,  5.8000e+01, -2.0460e+03,  1.5540e+03,
         1.3292e+04, -1.1048e+04,  2.3230e+03,  4.6210e+03, -2.5300e+03],
       [ 8.6860e+03, -1.5782e+04,  9.4250e+03, -1.5430e+03,  9.6230e+03,
         1.7105e+04, -1.5914e+04,  1.1736e+04, -2.8104e+04, -3.6897e+04,
        -1.3699e+04,  2.0553e+04,  1.9991e+04,  3.2136e+04, -3.5480e+03,
        -1.8253e+04, -8.9950e+03, -3.0098e+04,  1.2700e+04,  1.3554e+04],
       [-3.8530e+03,  6.6510e+03,  1.8075e+04,  7.3700e+03, -2.4656e+04,
        -2.9246e+04, -2.6536e+04, -9.6360e+03,  3.3764e+04,  1.1096e+04,
        -2.1650e+03,  1.4674e+04, -7.9150e+03, -1.7240e+04, -1.8694e+04,
        -3.2213e+04,  3.6956e+04,  2.3385e+04, -2.4675e+04,  2.9840e+03],
       [ 5.8920e+03,  1.1307e+04, -1.6295e+04, -1.2467e+04, -1.3780e+03,
        -2.4240e+03,  6.1143e+04,  9.2690e+03, -

In [410]:
np.array_equal(new_trans_convoluted_results,trans_convoluted_results)

False

In [411]:
new_trans_convoluted_results = np.zeros((matrix_size+4,matrix_size+4))
lower_bound0 = matrix_size + 4
lower_bound1 = matrix_size + 5
lower_bound2 = matrix_size + 6
lower_bound3 = matrix_size + 7

for img_ytr in range(matrix_size+4):
    for img_xptr in range(matrix_size+4):
        conv = 0
        if(img_yptr ==2 and img_xptr == 0): print("DEBUG")
        for k_yptr in range(5):
            # for k_xptr in range(5):
                idx_y = img_ytr + k_yptr
                idx_x_0 = img_xptr + 0
                idx_x_1 = img_xptr + 1
                idx_x_2 = img_xptr + 2
                idx_x_3 = img_xptr + 3
                idx_x_4 = img_xptr + 4
                # 0
                if idx_y == 0 or idx_y == 1 or idx_y == 2 or \
                    idx_y == 3 or idx_x_0 == 0 or idx_x_0 == 1 \
                    or idx_x_0 == 2 or idx_x_0 == 3:
                        conv += 0
                elif idx_y == lower_bound0 or idx_y == lower_bound1 or idx_y == lower_bound2 or idx_y == lower_bound3 \
                    or idx_x_0 == lower_bound0 or idx_x_0 == lower_bound1 or idx_x_0 == lower_bound2 or idx_x_0 == lower_bound3 :
                        conv += 0
                else:
                   conv += kernal[4-k_yptr,4] * img[idx_y-4,idx_x_0-4]
                # 1
                if idx_y == 0 or idx_y == 1 or idx_y == 2 or \
                    idx_y == 3 or idx_x_1 == 0 or idx_x_1 == 1 \
                    or idx_x_1 == 2 or idx_x_1 == 3:
                        conv += 0
                elif idx_y == lower_bound0 or idx_y == lower_bound1 or idx_y == lower_bound2 or idx_y == lower_bound3 \
                    or idx_x_1 == lower_bound0 or idx_x_1 == lower_bound1 or idx_x_1 == lower_bound2 or idx_x_1 == lower_bound3 :
                        conv += 0
                else:
                   conv += kernal[4-k_yptr,3] * img[idx_y-4,idx_x_1-4]
                # 2
                if idx_y == 0 or idx_y == 1 or idx_y == 2 or \
                    idx_y == 3 or idx_x_2 == 0 or idx_x_2 == 1 \
                    or idx_x_2 == 2 or idx_x_2 == 3:
                        conv += 0
                elif idx_y == lower_bound0 or idx_y == lower_bound1 or idx_y == lower_bound2 or idx_y == lower_bound3 \
                    or idx_x_2 == lower_bound0 or idx_x_2 == lower_bound1 or idx_x_2 == lower_bound2 or idx_x_2 == lower_bound3 :
                        conv += 0
                else:
                   conv += kernal[4-k_yptr,2] * img[idx_y-4,idx_x_2-4]
                # 3
                if idx_y == 0 or idx_y == 1 or idx_y == 2 or \
                    idx_y == 3 or idx_x_3 == 0 or idx_x_3 == 1 \
                    or idx_x_3 == 2 or idx_x_3 == 3:
                        conv += 0
                elif idx_y == lower_bound0 or idx_y == lower_bound1 or idx_y == lower_bound2 or idx_y == lower_bound3 \
                    or idx_x_3 == lower_bound0 or idx_x_3 == lower_bound1 or idx_x_3 == lower_bound2 or idx_x_3 == lower_bound3 :
                        conv += 0
                else:
                   conv += kernal[4-k_yptr,1] * img[idx_y-4,idx_x_3-4]

                # 4
                if idx_y == 0 or idx_y == 1 or idx_y == 2 or \
                    idx_y == 3 or idx_x_4 == 0 or idx_x_4 == 1 \
                    or idx_x_4 == 2 or idx_x_4 == 3:
                        conv += 0
                elif idx_y == lower_bound0 or idx_y == lower_bound1 or idx_y == lower_bound2 or idx_y == lower_bound3 \
                    or idx_x_4 == lower_bound0 or idx_x_4 == lower_bound1 or idx_x_4 == lower_bound2 or idx_x_4 == lower_bound3 :
                        conv += 0
                else:
                   conv += kernal[4-k_yptr,0] * img[idx_y-4,idx_x_4-4]

        new_trans_convoluted_results[img_ytr,img_xptr] = conv


In [412]:
new_trans_convoluted_results

array([[-1.4500e+03, -1.3100e+02,  8.6400e+02, -5.1300e+02,  2.0130e+03,
        -7.3550e+03,  2.9970e+03,  2.4240e+03,  5.4920e+03,  5.5870e+03,
         3.8600e+02, -1.0840e+03, -6.2430e+03, -1.9070e+03, -3.2210e+03,
         7.6050e+03,  2.7860e+03,  1.1460e+03, -4.9700e+02, -1.8400e+03],
       [ 2.4050e+03, -1.3300e+03,  5.4300e+02, -4.4000e+03,  7.4210e+03,
         8.6420e+03,  1.0065e+04,  3.1290e+03, -1.9108e+04, -1.8562e+04,
        -1.9094e+04, -7.1370e+03,  1.4760e+03,  2.1894e+04,  1.2440e+04,
        -8.6400e+02, -1.0459e+04, -2.1909e+04,  6.3100e+02,  3.5220e+03],
       [ 1.8730e+03,  2.9800e+02,  2.3130e+03,  1.5773e+04,  8.3900e+02,
        -1.3181e+04, -2.2772e+04, -3.4737e+04,  2.5960e+03, -7.6800e+02,
        -7.1490e+03,  2.3890e+04,  2.1565e+04, -6.0100e+02, -1.6846e+04,
        -3.1741e+04, -5.5460e+03,  1.5441e+04,  2.2000e+03,  1.8640e+03],
       [-5.9240e+03,  1.9002e+04,  6.1270e+03, -3.6520e+03, -3.5584e+04,
        -3.4679e+04,  5.6182e+04,  2.7631e+04,  

#### Convert results to LSB binary representation

In [413]:
twocomplement(57,20)

'00000000000000111001'

In [414]:
vf = np.vectorize(twocomplement)
bits_result = vf(trans_convoluted_results,20)

In [415]:
bits_result[0][0]

'00000000001110100000'

In [416]:
result = bits_result[0][0]

In [417]:
result = result[::-1]

In [418]:
result

'00000101110000000000'