In [21]:
import numpy as np
import copy
from queue import Queue
MAP_SIZE = 16
path_map = np.array([[0 for y in range(MAP_SIZE)] for x in range(MAP_SIZE)])
location_map = np.array([[0 for y in range(MAP_SIZE)] for x in range(MAP_SIZE)])

# Framing , double fan out, pick points


# (x,y)
# Assign example location map
# Macro 1
location_map[2:4,10:14] = 9
location_map[10:12,4:6] = 9
# Macro 2
location_map[2:5,2:6] = 4
location_map[12:14,11:14] = 4

In [22]:
path_map = copy.deepcopy(location_map)

In [23]:
location_map

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 4, 4, 4, 4, 0, 0, 0, 0, 9, 9, 9, 9, 0, 0],
       [0, 0, 4, 4, 4, 4, 0, 0, 0, 0, 9, 9, 9, 9, 0, 0],
       [0, 0, 4, 4, 4, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 9, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 9, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [24]:
path_map

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 4, 4, 4, 4, 0, 0, 0, 0, 9, 9, 9, 9, 0, 0],
       [0, 0, 4, 4, 4, 4, 0, 0, 0, 0, 9, 9, 9, 9, 0, 0],
       [0, 0, 4, 4, 4, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 9, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 9, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [25]:
## Given net_id,loc_x and loc_y
net_id_1 = 9
src_x_1 = 5  #source
src_y_1 = 10
dst_x_1 = 11 #sink
dst_y_1 = 3

net_id_2 = 4
src_x_2 = 4  #source
src_y_2 = 2
dst_x_2 = 13 # sink
dst_y_2 = 13

In [26]:
path_map_nxt = copy.deepcopy(path_map)

In [27]:
def adjacent_has_1_2(path_map,dst_y,dst_x):
    if path_map[dst_y+1,dst_x] == 1 or path_map[dst_y-1,dst_x]==1 or \
       path_map[dst_y,dst_x+1]==1 or path_map[dst_y,dst_x-1]==1 \
       or path_map[dst_y+1,dst_x] == 2 or path_map[dst_y-1,dst_x]==2 or \
       path_map[dst_y,dst_x+1]==2 or path_map[dst_y,dst_x-1]==2:
        return True
    else:
        return False

In [28]:
def fillpath(src_x,src_y,dst_x,dst_y,location_map,path_map):
    # Initailize source
    cur_y = src_y
    cur_x = src_x
    for neighbor in [[cur_y+1,cur_x],[cur_y-1,cur_x],[cur_y,cur_x+1],[cur_y,cur_x-1]]:
        neighbor_x = neighbor[1]
        neighbor_y = neighbor[0]
        if location_map[neighbor_y,neighbor_x] == 0 and path_map[neighbor_y,neighbor_x] == 0:
            path_map[neighbor_y,neighbor_x] = 1

    cnt = 1
    path_map_nxt = copy.deepcopy(path_map)
    while True:
        if cnt == 4:
            cnt = 0

        if adjacent_has_1_2(path_map,dst_y,dst_x):
            return path_map

        for cur_y in range(1,MAP_SIZE-1):
            for cur_x in range(1,MAP_SIZE-1):
                if location_map[cur_y,cur_x] == 0 and path_map[cur_y,cur_x] == 0:
                    # Down,up,right,left
                    if adjacent_has_1_2(path_map,cur_y,cur_x):
                        if cnt == 0:
                            path_map_nxt[cur_y,cur_x] = 1
                        elif cnt == 1:
                            path_map_nxt[cur_y,cur_x] = 1
                        elif cnt == 2:
                            path_map_nxt[cur_y,cur_x] = 2
                        elif cnt == 3:
                            path_map_nxt[cur_y,cur_x] = 2

        # print(path_map_nxt)
        path_map = copy.deepcopy(path_map_nxt)
        cnt += 1

In [29]:
path_map = fillpath(src_x_1,src_y_1,dst_x_1,dst_y_1,location_map,path_map)

In [30]:
path_map

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 2, 2, 1, 2, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 4, 4, 4, 4, 1, 1, 2, 2, 9, 9, 9, 9, 0, 0],
       [0, 2, 4, 4, 4, 4, 2, 1, 1, 2, 9, 9, 9, 9, 0, 0],
       [0, 1, 4, 4, 4, 4, 2, 2, 1, 1, 2, 2, 0, 0, 0, 0],
       [0, 1, 2, 2, 1, 1, 1, 2, 2, 1, 1, 2, 2, 0, 0, 0],
       [0, 2, 2, 1, 1, 2, 1, 1, 2, 2, 1, 1, 2, 2, 0, 0],
       [0, 2, 1, 1, 2, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 0],
       [0, 1, 1, 2, 2, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 0],
       [0, 1, 2, 2, 1, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 0],
       [0, 1, 1, 2, 9, 9, 1, 1, 2, 2, 1, 1, 2, 2, 1, 0],
       [0, 2, 1, 1, 9, 9, 1, 2, 2, 1, 1, 2, 2, 1, 1, 0],
       [0, 2, 2, 1, 1, 2, 2, 2, 1, 1, 2, 4, 4, 4, 2, 0],
       [0, 1, 2, 2, 1, 1, 2, 1, 1, 2, 2, 4, 4, 4, 2, 0],
       [0, 1, 1, 2, 2, 1, 1, 1, 2, 2, 1, 1, 2, 2, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [31]:
def retrace_path(src_x,src_y,dst_x,dst_y,location_map,path_map):
    # Find the first label and starting seq from dst, implement FSM in python
    cur_x   = dst_x
    cur_y   = dst_y
    # Down
    if path_map[cur_y+1,cur_x] == 1 or path_map[cur_y+1,cur_x] == 2:
        cur_seq = path_map[cur_y+1,cur_x]
        cur_y = cur_y + 1
    # Up
    elif path_map[cur_y-1,cur_x] == 1 or path_map[cur_y-1,cur_x] == 2:
        cur_seq = path_map[cur_y-1,cur_x]
        cur_y = cur_y-1
    # Right
    elif path_map[cur_y,cur_x+1] == 1 or path_map[cur_y,cur_x+1] == 2:
        cur_seq = path_map[cur_y,cur_x+1]
        cur_x = cur_x+1
    # Left
    elif path_map[cur_y,cur_x-1] == 1 or path_map[cur_y,cur_x-1] == 2:
        cur_seq = path_map[cur_y,cur_x-1]
        cur_x = cur_x-1

    location_map[cur_y,cur_x] = 3

    # If src is 2
    if cur_seq == 2:
        # Neighbor is 2
        # Down
        if path_map[cur_y+1,cur_x] == 2:
            cur_seq = path_map[cur_y+1,cur_x]
            cur_y = cur_y + 1
            cnt = 1
        # Down
        elif path_map[cur_y+1,cur_x] == 1:
            cur_seq = path_map[cur_y+1,cur_x]
            cur_y = cur_y + 1
            cnt = 2
        # Up
        elif path_map[cur_y-1,cur_x] == 2:
            cur_seq = path_map[cur_y-1,cur_x]
            cur_y = cur_y-1
            cnt = 1
        # Up
        elif path_map[cur_y-1,cur_x] == 1:
            cur_seq = path_map[cur_y-1,cur_x]
            cur_y = cur_y-1
            cnt = 2
        # Right
        elif path_map[cur_y,cur_x+1] == 2:
            cur_seq = path_map[cur_y,cur_x+1]
            cur_x = cur_x+1
            cnt = 1
        # Right
        elif path_map[cur_y,cur_x+1] == 1:
            cur_seq = path_map[cur_y,cur_x+1]
            cur_x = cur_x+1
            cnt = 2
        # Left
        elif path_map[cur_y,cur_x-1] == 2:
            cur_seq = path_map[cur_y,cur_x-1]
            cur_x = cur_x-1
            cnt = 1
        # Left
        elif path_map[cur_y,cur_x-1] == 1:
            cur_seq = path_map[cur_y,cur_x-1]
            cur_x = cur_x-1
            cnt = 2

    # If src is 1
    elif cur_seq == 1:
        # Neighbor is 2
        # Down
        if path_map[cur_y+1,cur_x] == 2:
            cur_seq = path_map[cur_y+1,cur_x]
            cur_y = cur_y + 1
            cnt = 0
        # Neighbor is 1
        # Down
        elif path_map[cur_y+1,cur_x] == 1:
            cur_seq = path_map[cur_y+1,cur_x]
            cur_y = cur_y + 1
            cnt = 3
        # Up
        elif path_map[cur_y-1,cur_x] == 2:
            cur_seq = path_map[cur_y-1,cur_x]
            cur_y = cur_y-1
            cnt = 0
        # Up
        elif path_map[cur_y-1,cur_x] == 1:
            cur_seq = path_map[cur_y-1,cur_x]
            cur_y = cur_y-1
            cnt = 3
        # Right
        elif path_map[cur_y,cur_x+1] == 2:
            cur_seq = path_map[cur_y,cur_x+1]
            cur_x = cur_x+1
            cnt = 0
        # Right
        elif path_map[cur_y,cur_x+1] == 1:
            cur_seq = path_map[cur_y,cur_x+1]
            cur_x = cur_x+1
            cnt = 3
        # Left
        elif path_map[cur_y,cur_x-1] == 2:
            cur_seq = path_map[cur_y,cur_x-1]
            cur_x = cur_x-1
            cnt = 0
        # Left
        elif path_map[cur_y,cur_x-1] == 1:
            cur_seq = path_map[cur_y,cur_x-1]
            cur_x = cur_x-1
            cnt = 3

    location_map[cur_y,cur_x] = 3

    while True:
        location_map[cur_y,cur_x] = 3

        if (cur_y+1 ==src_y and cur_x == src_x) or (cur_y-1 == src_y and cur_x == src_x) or (cur_y==src_y and cur_x+1 == src_x)\
        or (cur_y == src_y and cur_x-1 == src_x):
            return

        if cnt == 0 or cnt == 3: # Expect 2
            # Down
            if path_map[cur_y+1,cur_x] == 2:
                cur_seq = path_map[cur_y+1,cur_x]
                cur_y = cur_y + 1
            # Up
            elif path_map[cur_y-1,cur_x] == 2:
                cur_seq = path_map[cur_y-1,cur_x]
                cur_y = cur_y-1
            # Right
            elif path_map[cur_y,cur_x+1] == 2:
                cur_seq = path_map[cur_y,cur_x+1]
                cur_x = cur_x+1
            # Left
            elif path_map[cur_y,cur_x-1] == 2:
                cur_seq = path_map[cur_y,cur_x-1]
                cur_x = cur_x-1

        elif cnt == 1 or cnt == 2: # Expect 1
            # Down
            if path_map[cur_y+1,cur_x] == 1:
                cur_seq = path_map[cur_y+1,cur_x]
                cur_y = cur_y + 1
            # Up
            elif path_map[cur_y-1,cur_x] == 1:
                cur_seq = path_map[cur_y-1,cur_x]
                cur_y = cur_y-1
            # Right
            elif path_map[cur_y,cur_x+1] == 1:
                cur_seq = path_map[cur_y,cur_x+1]
                cur_x = cur_x+1
            # Left
            elif path_map[cur_y,cur_x-1] == 1:
                cur_seq = path_map[cur_y,cur_x-1]
                cur_x = cur_x-1

        cnt += 1
        cnt = cnt % 4

In [32]:
retrace_path(src_x_1,src_y_1,dst_x_1,dst_y_1,location_map,path_map)

In [33]:
location_map

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 4, 4, 4, 4, 0, 0, 0, 0, 9, 9, 9, 9, 0, 0],
       [0, 0, 4, 4, 4, 4, 0, 0, 0, 0, 9, 9, 9, 9, 0, 0],
       [0, 0, 4, 4, 4, 4, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0],
       [0, 0, 0, 0, 9, 9, 3, 3, 3, 3, 3, 3, 0, 0, 0, 0],
       [0, 0, 0, 0, 9, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [34]:
path_map =copy.deepcopy(location_map)

In [35]:
path_map

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 4, 4, 4, 4, 0, 0, 0, 0, 9, 9, 9, 9, 0, 0],
       [0, 0, 4, 4, 4, 4, 0, 0, 0, 0, 9, 9, 9, 9, 0, 0],
       [0, 0, 4, 4, 4, 4, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0],
       [0, 0, 0, 0, 9, 9, 3, 3, 3, 3, 3, 3, 0, 0, 0, 0],
       [0, 0, 0, 0, 9, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [36]:
net_id_2 = 4
src_x_2 = 4  #source
src_y_2 = 2
dst_x_2 = 13 # sink
dst_y_2 = 13

In [37]:
path_map = fillpath(src_x_2,src_y_2,dst_x_2,dst_y_2,location_map,path_map)

In [38]:
path_map

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 2, 1, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 0],
       [0, 1, 4, 4, 4, 4, 2, 1, 1, 2, 9, 9, 9, 9, 2, 0],
       [0, 1, 4, 4, 4, 4, 1, 1, 2, 2, 9, 9, 9, 9, 1, 0],
       [0, 2, 4, 4, 4, 4, 1, 2, 2, 1, 1, 3, 2, 2, 1, 0],
       [0, 2, 1, 1, 1, 2, 2, 2, 1, 1, 2, 3, 1, 2, 2, 0],
       [0, 1, 1, 2, 1, 1, 2, 1, 1, 2, 2, 3, 1, 1, 2, 0],
       [0, 1, 2, 2, 2, 1, 1, 1, 2, 2, 1, 3, 2, 1, 1, 0],
       [0, 2, 2, 1, 2, 2, 1, 2, 2, 1, 1, 3, 2, 2, 1, 0],
       [0, 2, 1, 1, 1, 2, 2, 2, 1, 1, 2, 3, 1, 2, 2, 0],
       [0, 1, 1, 2, 9, 9, 3, 3, 3, 3, 3, 3, 1, 1, 2, 0],
       [0, 1, 2, 2, 9, 9, 1, 1, 2, 0, 0, 0, 2, 1, 1, 0],
       [0, 2, 2, 1, 1, 2, 2, 1, 1, 2, 0, 4, 4, 4, 1, 0],
       [0, 2, 1, 1, 2, 2, 1, 1, 2, 0, 0, 4, 4, 4, 2, 0],
       [0, 1, 1, 2, 2, 1, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [39]:
retrace_path(src_x_2,src_y_2,dst_x_2,dst_y_2,location_map,path_map)

In [40]:
location_map

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0],
       [0, 0, 4, 4, 4, 4, 0, 0, 0, 0, 9, 9, 9, 9, 3, 0],
       [0, 0, 4, 4, 4, 4, 0, 0, 0, 0, 9, 9, 9, 9, 3, 0],
       [0, 0, 4, 4, 4, 4, 0, 0, 0, 0, 0, 3, 0, 0, 3, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 3, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 3, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 3, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 3, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 3, 0],
       [0, 0, 0, 0, 9, 9, 3, 3, 3, 3, 3, 3, 0, 0, 3, 0],
       [0, 0, 0, 0, 9, 9, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 3, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 3, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])