In [1]:
import numpy as np
import copy
from queue import Queue
MAP_SIZE = 16
path_map = np.array([[0 for y in range(MAP_SIZE)] for x in range(MAP_SIZE)])
location_map = np.array([[0 for y in range(MAP_SIZE)] for x in range(MAP_SIZE)])

# Framing , double fan out, pick points


# (x,y)
# Assign example location map
# Macro 1
location_map[2:4,10:14] = 9
location_map[10:12,4:6] = 9
# Macro 2
location_map[2:5,2:6] = 4
location_map[12:14,11:14] = 4

In [2]:
path_map = copy.deepcopy(location_map)

In [3]:
location_map

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 4, 4, 4, 4, 0, 0, 0, 0, 9, 9, 9, 9, 0, 0],
       [0, 0, 4, 4, 4, 4, 0, 0, 0, 0, 9, 9, 9, 9, 0, 0],
       [0, 0, 4, 4, 4, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 9, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 9, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [4]:
path_map

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 4, 4, 4, 4, 0, 0, 0, 0, 9, 9, 9, 9, 0, 0],
       [0, 0, 4, 4, 4, 4, 0, 0, 0, 0, 9, 9, 9, 9, 0, 0],
       [0, 0, 4, 4, 4, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 9, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 9, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [5]:
## Given net_id,loc_x and loc_y
net_id_1 = 9
src_x_1 = 5  #source
src_y_1 = 10
dst_x_1 = 11 #sink
dst_y_1 = 3

net_id_2 = 4
src_x_2 = 4  #source
src_y_2 = 2
dst_x_2 = 13 # sink
dst_y_2 = 13

In [6]:
def adjacent_has_1_2(path_map,dst_y,dst_x):
    if path_map[dst_y+1,dst_x] == 1 or path_map[dst_y-1,dst_x]==1 or \
       path_map[dst_y,dst_x+1]==1 or path_map[dst_y,dst_x-1]==1 \
       or path_map[dst_y+1,dst_x] == 2 or path_map[dst_y-1,dst_x]==2 or \
       path_map[dst_y,dst_x+1]==2 or path_map[dst_y,dst_x-1]==2:
        return True
    else:
        return False

In [7]:
def fillpath(src_x,src_y,dst_x,dst_y,location_map,path_map):
    # Initailize source
    cur_y = src_y
    cur_x = src_x
    for neighbor in [[cur_y+1,cur_x],[cur_y-1,cur_x],[cur_y,cur_x+1],[cur_y,cur_x-1]]:
        neighbor_x = neighbor[1]
        neighbor_y = neighbor[0]
        if location_map[neighbor_y,neighbor_x] == 0 and path_map[neighbor_y,neighbor_x] == 0:
            path_map[neighbor_y,neighbor_x] = 1

    cnt = 1
    while True:
        if cnt == 4:
            cnt = 1
        for cur_y in range(1,MAP_SIZE-1):
            for cur_x in range(1,MAP_SIZE-1):
                if cnt == 0:
                    if path_map[cur_y,cur_x] == 2:
                        for neighbor in [[cur_y+1,cur_x],[cur_y-1,cur_x],[cur_y,cur_x+1],[cur_y,cur_x-1]]:
                            neighbor_x = neighbor[1]
                            neighbor_y = neighbor[0]
                            if location_map[neighbor_y,neighbor_x] == 0 and path_map[neighbor_y,neighbor_x] == 0:
                                path_map[neighbor_y,neighbor_x] = 1
                elif cnt == 1:
                    if path_map[cur_y,cur_x] == 1:
                        for neighbor in [[cur_y+1,cur_x],[cur_y-1,cur_x],[cur_y,cur_x+1],[cur_y,cur_x-1]]:
                            neighbor_x = neighbor[1]
                            neighbor_y = neighbor[0]
                            if location_map[neighbor_y,neighbor_x] == 0 and path_map[neighbor_y,neighbor_x] == 0:
                                path_map[neighbor_y,neighbor_x] = 1
                elif cnt == 2:
                    if path_map[cur_y,cur_x] == 1:
                        for neighbor in [[cur_y+1,cur_x],[cur_y-1,cur_x],[cur_y,cur_x+1],[cur_y,cur_x-1]]:
                            neighbor_x = neighbor[1]
                            neighbor_y = neighbor[0]
                            if location_map[neighbor_y,neighbor_x] == 0 and path_map[neighbor_y,neighbor_x] == 0:
                                path_map[neighbor_y,neighbor_x] = 2
                elif cnt == 3:
                    if path_map[cur_y,cur_x] == 2:
                        for neighbor in [[cur_y+1,cur_x],[cur_y-1,cur_x],[cur_y,cur_x+1],[cur_y,cur_x-1]]:
                            neighbor_x = neighbor[1]
                            neighbor_y = neighbor[0]
                            if location_map[neighbor_y,neighbor_x] == 0 and path_map[neighbor_y,neighbor_x] == 0:
                                path_map[neighbor_y,neighbor_x] = 2

                if adjacent_has_1_2(path_map,dst_y,dst_x):
                    return

        cnt += 1

In [8]:
fillpath(src_x_1,src_y_1,dst_x_1,dst_y_1,location_map,path_map)

In [9]:
path_map

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 4, 4, 4, 4, 0, 0, 0, 0, 9, 9, 9, 9, 0, 0],
       [0, 0, 4, 4, 4, 4, 0, 0, 0, 0, 9, 9, 9, 9, 0, 0],
       [0, 0, 4, 4, 4, 4, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0],
       [0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0],
       [0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [0, 0, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2],
       [0, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 2, 2, 2, 9, 9, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 2, 2, 2, 9, 9, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 4, 4, 4, 1, 1],
       [0, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 4, 4, 4, 1, 1],
       [0, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0]])